function [fps, w1, w2] = call_gaussfilt(handles)
    mainfig_pos = get(handles.mainfigure, 'Position');
    defaultPara = handles.defaultPara.Denoise.gaussfilt;
    fps = defaultPara(1);
    w1 = defaultPara(2);
    w2 = defaultPara(3);
    % fps = 10;
    handles = loadtrace(handles, 1);
    [trace_stamp, trace_num, ttlabel1] = pooltrace_forGaussfilt(handles);
    trace_stamp = trace_stamp(:,1:min(trace_num,6));
    N = size(trace_stamp, 2);
    scrsz = handles.scrsz;
    pos = mainfig_pos;
    pos(1) = pos(1)+100;
    pos(3) = 200;
    pos(4) = pos(4)*0.8;
%     pos(4) = mainfig_pos(4)*0.6;
    hplot = figure(25); clf('reset')
    set(hplot, 'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...        
        'Name', 'Set up Gaussian filter', 'Position', pos);
    
    % list parameters
    panel1 = uipanel('Parent',hplot,'Title','Set up Gauss filt',...
        'Position',[0.05 0.35 0.9 0.6],...
        'FontSize', 10);
    % input variable for plot 
    uicontrol('Parent',panel1, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.05 0.8 0.8 0.15],...
        'FontSize', 10, ...
        'string', 'fps');
    fpsinput = uicontrol('Parent',panel1, 'Style','edit',...
        'Units', 'normalized',...
        'FontSize', 10, ...
        'Position',[0.05 0.75 0.8 0.1],...
        'String', fps);
    % input variable for plot 
    uicontrol('Parent',panel1, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.05 0.55 0.8 0.15],...
        'FontSize', 10, ...
        'string', 'Sginal filter size');
    w1_input = uicontrol('Parent',panel1, 'Style','edit',...
        'Units', 'normalized',...
        'FontSize', 10, ...
        'Position',[0.05 0.5 0.8 0.1],...
        'String', num2str(w1));
        % input variable for plot 
    uicontrol('Parent',panel1, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.05 0.2 0.8 0.15],...
        'FontSize', 10, ...
        'string', 'Baseline filter size');
    w2_input = uicontrol('Parent',panel1, 'Style','edit',...
        'Units', 'normalized',...
        'FontSize', 10, ...
        'Position',[0.05 0.15 0.8 0.1],...
        'String', num2str(w2));
    
    p1 = uicontrol(hplot,'style','pushbutton',...
        'Units', 'normalized',...
        'String', 'Show',...
        'position', [0.05 0.22 0.8 0.1],...
        'FontSize', 11, ...
        'Callback', @Testpress); 
    
    p2 = uicontrol(hplot,'style','pushbutton',...
        'Units', 'normalized',...
        'String', 'Accept',...
        'position', [0.05 0.1 0.8 0.1],...
        'FontSize', 11, ...
        'Callback', @Gopress); 
    
    uiwait(hplot)    
    %[fmodel, startpoint] = modelclass(funcsel);
    close(hplot)

    function Testpress(hObject, eventdata)
        if get(hObject, 'Value') == 1
            if ~isempty(get(fpsinput,'String'))
                fps = str2num(get(fpsinput,'String'));
                w1 = str2num(get(w1_input,'String'));
                w2 = str2num(get(w2_input,'String'));            
                [tc2, finalBaseline_out] = F_Preprocess_v2(trace_stamp',...
                    fps, 0, w1, w2);
                pos1 = mainfig_pos;
                pos1(1) = pos1(1)+200;
                pos1(2) = pos1(2)-100;
                pos1(3) = pos1(3)-100;
                hplot2 = figure(26); clf('reset')
                set(hplot2, 'NumberTitle', 'off', ...    
                    'Name', 'Gaussian filtered trace', 'Position', pos1);
                for i = 1:size(tc2,2)
                    ax1 = subplot(N,1,i, 'Parent', hplot2);
                    cla(ax1)
                    plot(ax1, trace_stamp(:,i),'color', [0.5, 0.5, 0.5], 'linewidth', 2)
                    hold on, plot(ax1, tc2(:,i), 'linewidth', 1)
                    hold on, plot(ax1, finalBaseline_out(i,:),'k') 
                    if i == 1
                        legend(ax1, {'raw', 'filtered', 'baseline'},...
                            'Orientation','horizontal', 'Location', 'north')
                    end                    
                end
            end
        end
    end

    function Gopress(hObject, eventdata)
        if get(hObject, 'Value') == 1
            fps = str2num(get(fpsinput,'String'));
            w1 = str2num(get(w1_input,'String'));
            w2 = str2num(get(w2_input,'String'));            
            uiresume;
            return
        end
    end
end