function calllochist(Dendrite_CrossSess, spine_evolve, handles)
    binvalue = handles.thresh*2;    
    dendID = table2array(Dendrite_CrossSess(:,1));
    dendID(dendID==0) = [];
    dendID(isnan(dendID)) = [];
    targetID = dendID(1);
    
    DendLoc = table2array(Dendrite_CrossSess);
    SpineLoc = table2array(spine_evolve);   
    NumSess = length(handles.datafilename);
    
    pos = [50, 400, 1000, 600];
    hplot = figure(35); clf('reset')
    set(hplot, 'NumberTitle', 'off', ...
        'MenuBar', 'figure', ...        
        'Toolbar', 'figure',...
        'Name', 'Spine distribution on dendrites', 'Position', pos);   

    % list parameters
    panel1 = uipanel('Parent',hplot,...
        'Position',[0.05 0.88 0.75 0.1],...
        'FontSize', 10);
    uicontrol('Parent',panel1, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.05 0.05 0.15 0.7],...
        'FontSize', 10, ...
        'string', 'Dendrite:');       
    datalist = uicontrol('Parent',panel1, 'Style', 'popupmenu',...
        'Units', 'normalized',...
        'Position',[0.25 0.05 0.15 0.7],...
        'FontSize', 10, ...
        'max', length(dendID),...
        'string', num2str(dendID));
        
    uicontrol('Parent',panel1, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.45 0.05 0.15 0.7],...
        'FontSize', 10, ...
        'string', 'Bin (pixel):'); 
    answer = uicontrol('Parent',panel1, 'Style', 'edit',...
        'Units', 'normalized',...
        'Position',[0.65 0.18 0.15 0.6],...
        'FontSize', 10, 'Max', 1,...
        'String', num2str(binvalue));
    
    % pushbutton
    uicontrol('Parent',panel1,'style','pushbutton',...
        'Units', 'normalized',...
        'String', 'Go',...
        'position', [0.85 0.1 0.1 0.8],...
        'FontSize', 11, ...
        'Callback', @Gopress);   
        
    % pushbutton    
    uicontrol(hplot,'style','pushbutton',...
        'Units', 'normalized',...
        'String', 'Close',...
        'position', [0.85 0.9 0.1 0.08],...
        'FontSize', 11, 'ForegroundColor', 'r',...
        'Callback', @Finishpress);
    
    panel2 = uipanel('Parent',hplot,...
        'Position',[0.05 0.05 0.45 0.8],...
        'FontSize', 10);
    ax1 = axes('Parent',panel2); 
    panel3 = uipanel('Parent',hplot,...
        'Position',[0.5 0.05 0.45 0.8],...
        'FontSize', 10);
    ax2 = axes('Parent',panel3); 
    DendriticSpine_hist(handles, ax1, ax2, ...
        targetID, binvalue, spine_evolve, Dendrite_CrossSess)    
    
    uiwait(hplot)
    close(hplot)
    
    function Gopress(hObject, eventdata)
        if get(hObject, 'Value') == 1  
            targetID = dendID(datalist.Value);
            if ~isempty(str2num(get(answer,'String')))
                binvalue = max(0, str2num(get(answer,'String')));
            else
                binvalue = handles.thresh*2;
                set(answer, 'String', num2str(binvalue))
            end
            DendriticSpine_hist(handles, ax1, ax2,...
                targetID, binvalue, spine_evolve, Dendrite_CrossSess)    
        end
    end

    function Finishpress(hObject, eventdata)
        if get(hObject, 'Value') == 1  
            uiresume;
            return
        end
    end
end