function [neusel] = prepPlottrace(handles, ttlabel, mainfig_pos)
    neusel = [];
    pos = mainfig_pos;
    pos(1) = pos(1)+100;
    pos(3) = pos(3)-400;
    pos(4) = pos(4)-200;
    hplot = figure(25); clf('reset')
    set(hplot, 'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...        
        'Name', 'Set up for plotting traces', 'Position', pos);
   
    % trace list
    uicontrol(hplot, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.1 0.9 0.2 0.05],...
        'FontSize', 10, ...
        'string', 'Select traces for plot');

    neulist = uitable(hplot,'Data',ttlabel,...
        'Units', 'normalized',...
        'Position',[0.1 0.25 0.8 0.6],...
        'ColumnName', handles.datafilename,...
        'RowName', [], ...
        'CellSelection',@getidx);

    % pushbutton
    p = uicontrol(hplot,'style','pushbutton',...
        'Units', 'normalized',...
        'String', 'Go',...
        'position', [0.6 0.1 0.2 0.05],...
        'FontSize', 11, ...
        'Callback', @Gopress); 
    
    uiwait(hplot)
    close(hplot)

    function getidx(hObject, eventdata)
        neusel = eventdata.Indices;
        assignin('base', 'neusel', neusel)
    end
    
    function Gopress(hObject, eventdata)
        if get(hObject, 'Value') == 1
            uiresume;
            return
        end
    end
end
