function funcsel = prepCrossSessReg(handles)
    funcsel = [];
    pos = get(handles.mainfigure, 'Position');
    scrsz = handles.scrsz;
    pos(1) = pos(1)+100;
    pos(3) = 300;
    pos(4) = 300;
    hplot = figure(25); clf('reset') 
    set(hplot, 'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...        
        'Name', 'Cross-session mapping', 'Position', pos);
    
        % select fitting function
    rb1 = 'Register to the last dataset';
    rb2 = 'Register to dataset 1';     
    rb3 = 'Use existing transform matrix'; 
    
    uicontrol(hplot, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.1 0.65 0.8 0.2],...
        'FontSize', 10, ...
        'string', 'Select a mapping method');
    funclist = {rb1, rb2, rb3};
    fpopup = uicontrol(hplot, 'Style', 'popupmenu',...
        'Units', 'normalized',...
        'Position',[0.1 0.5 0.8 0.2],...
        'FontSize', 10, ...
        'string', funclist, ...
        'Callback', @fpopup_sel);  
        
    % pushbutton
    p = uicontrol(hplot,'style','pushbutton',...
        'Units', 'normalized',...
        'String', 'Go',...
        'position', [0.5 0.2 0.3 0.15],...
        'FontSize', 11, ...
        'Callback', @Gopress); 
    
    uiwait(hplot)
    close(hplot)
    
    function fpopup_sel(hObject, eventdata)
        funcsel = get(hObject, 'value');
    end

    function Gopress(hObject, eventdata)
        if get(hObject, 'Value') == 1
            uiresume;
            return
        end
    end
end