function stampsel = prepStampRespPlot(handles)
scrsz = handles.scrsz;
pos = round([50 scrsz(4)*0.4 400 300]);
stampinfo = handles.stampinfo;
N = length(stampinfo);
hplot = figure(25); clf('reset')
set(hplot, 'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Name', 'Set up fitting', 'Position', pos);

uicontrol(hplot, 'Style', 'text',...
    'Position',[10 250 180 20],...
    'FontSize', 10, ...
    'string', 'Select stamp for fitting');

slist = uicontrol(hplot, 'Style', 'listbox',...
    'Position',[25 45 180 200],...
    'FontSize', 10, ...
    'max', N,...
    'string',stampinfo);

p = uicontrol(hplot,'style','pushbutton',...
    'String', 'Go',...
    'position', [280 50 100 30],...
    'FontSize', 10, ...
    'Callback', 'uiresume(gcbf)'); 
uiwait(hplot)
stampsel = get(slist,'value');
close(hplot)
