function [stampsel, varsel, trialsel, trialIDsel, condsel, plotwin,...
    neusel, dosave, varNames] = ...
    prepBehResp(handles, ttlabel, mainfig_pos)
    dosave = 0;
    varsel = [1, 1];
    stampsel = '';
    trialsel = '';
    condsel = '';
    plotwin = '';
    trialIDsel = [];
    neusel = [];
    varlist = {'None'};

    stampinfo = handles.stampinfo{1};
    varNames = stampinfo.Properties.VariableNames;    
    N = length(varNames);
    
    scrsz = handles.scrsz;
    pos = mainfig_pos;
    pos(1) = pos(1)+100;
    pos(3) = pos(3)-200;
    hplot = figure(25); clf('reset')
    set(hplot, 'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...        
        'Name', 'Set up feature analysis', 'Position', pos);
    
    % list parameters
    panel1 = uipanel('Parent',hplot,'Title','Plot for parameter k',...
        'Position',[0.05 0.7 0.3 0.25],...
        'FontSize', 10);
    stmplist = uicontrol('Parent',panel1, 'Style', 'popupmenu',...
        'Units', 'normalized',...
        'Position',[0.05 0.8 0.9 0.08],...
        'FontSize', 10, ...
        'max', N,...
        'string',varNames,...
        'Callback', @updatevarPopup);
    % input variable for plot 
    uicontrol('Parent',panel1, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.05 0.35 0.2 0.1],...
        'FontSize', 10, ...
        'string', 'k');

    velgrad = uicontrol('Parent',panel1, 'Style', 'popupmenu',...
        'Units', 'normalized',...
        'Position',[0.2 0.4 0.3 0.08],...
        'FontSize', 10, ...
        'max', N,...
        'string',{'','=', '<', '>'},...
        'Callback', @updatevargrad); 

    varlist = table2array(unique(stampinfo(:,1)));
    fpopup = uicontrol('Parent',panel1, 'Style', 'popupmenu',...
        'Units', 'normalized',...
        'Position',[0.6 0.4 0.3 0.08],...
        'FontSize', 10, ...
        'string', varlist, ...
        'Callback', @fpopup_sel);    
    
    % with or without trial average
    panel2 = uipanel('Parent',hplot,'Title','With trial structure',...
        'Position',[0.05 0.4 0.3 0.25],...
        'FontSize', 10);

    txt0 = uicontrol('Parent',panel2, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.05 0.7 0.25 0.15],...
        'FontSize', 10, ...
        'string', 'Trial ID');
    iftriallist = uicontrol('Parent',panel2, 'Style', 'popupmenu',...
        'Units', 'normalized',...
        'Position',[0.35 0.8 0.55 0.08],...
        'FontSize', 10, ...
        'max', N+1,...
        'string', ['None', varNames],...
        'Callback', @trialpopup_sel);
    
    txt1 = uicontrol('Parent',panel2, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.05 0.38 0.5 0.3],...
        'FontSize', 10, ...
        'string', 'Select trial: 1-4, 10');
    t = uicontrol('Parent',panel2, 'Style', 'edit',...
        'Units', 'normalized',...
        'Position',[0.6 0.4 0.3 0.25],...
        'FontSize', 10, 'Max', 1);   
    
    txt2 = uicontrol('Parent',panel2, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.05 0.1 0.38 0.15],...
        'FontSize', 10, ...
        'string', 'Condition');
    ifcond = uicontrol('Parent',panel2, 'Style', 'popupmenu',...
        'Units', 'normalized',...
        'Position',[0.45 0.2 0.45 0.08],...
        'FontSize', 10, ...
        'max', N+1,...
        'string', ['None', varNames],...
        'Callback', @condpopup_sel);
    
    % user define time window for plot
    panel3 = uipanel('Parent',hplot,'Title','Time window for plot, [0-2]',...
        'Position',[0.05 0.1 0.3 0.25],...
        'FontSize', 10);
    
    % example plot
    x = -1:0.1:5;
    y = (1.5-0.5*exp(-x/1)).*(2*exp(-x/2));
    ax = axes('Parent',panel3);    
    plot(ax, x, y); box off
    xlabel('Time from k=v')
    patch([0,2,2,0],[0,0,2.2,2.2], [1,0,0],'FaceAlpha',0.2, 'EdgeColor', 'none')
    
    fdur = uicontrol('Parent',panel3, 'Style', 'edit',...
        'Units', 'normalized',...
        'Position',[0.6 0.5 0.3 0.3],...
        'FontSize', 10, 'Max', 1); 
    
    % trace list
    uicontrol(hplot, 'Style', 'text',...
        'Units', 'normalized',...
        'Position',[0.4 0.9 0.2 0.05],...
        'FontSize', 10, ...
        'string', 'Select traces');

    neulist = uitable(hplot,'Data',ttlabel,...
        'Units', 'normalized',...
        'Position',[0.4 0.3 0.55 0.6],...
        'ColumnName', handles.datafilename,...
        'RowName', [], ...
        'CellSelection',@getidx);
    
%     % summarize user input 
%     h_textbox = uicontrol(hplot, 'Style','edit',...
%             'Units', 'normalized',...
%             'FontSize', 10, ...
%             'Position',[0.4 0.3 0.55 0.12],...
%             'String', 'No variable selected');

    % saving data
    scheck = uicontrol(hplot, 'Style','checkbox',...
            'Units', 'normalized',...
            'FontSize', 10, ...
            'Position',[0.45 0.1 0.2 0.05], ...
            'String', 'Save Data', ...
            'Value', 0);
        
    % pushbutton
    p = uicontrol(hplot,'style','pushbutton',...
        'Units', 'normalized',...
        'String', 'Go',...
        'position', [0.7 0.1 0.2 0.05],...
        'FontSize', 11, ...
        'Callback', @Gopress); 
    
    uiwait(hplot)
    close(hplot)

    function getidx(hObject, eventdata)
        neusel = eventdata.Indices;
%         assignin('base', 'neusel', neusel)
    end
    function updatevarPopup(src, ~)
        stampsel = stmplist.String{stmplist.Value};
        varlist = table2array(unique(stampinfo(:,stmplist.Value)));
        fpopup.String = varlist;
    end
    function updatevargrad(src, ~)
        varsel(1) = velgrad.Value;
    end
    function fpopup_sel(hObject, ~)
        varsel1 = get(hObject, 'value');
        varsel(2) = varsel1;
    end
    function trialpopup_sel(hObject, ~)
        varsel1 = get(hObject, 'value');
        if varsel1>1
            trialsel = iftriallist.String{varsel1};
        else
            trialsel = [];
        end
    end
    function condpopup_sel(hObject, ~)
        varsel1 = get(hObject, 'value');
        condsel = ifcond.String{varsel1};
    end
    function Gopress(hObject, eventdata)
        if get(hObject, 'Value') == 1
            trialIDsel = get(t, 'String');
            plotwin = get(fdur, 'String');
            dosave = get(scheck, 'value');        
            if isempty(varsel)
                varsel(1) = 1;
                varsel(2) = str2num(fpopup.String(1));
            end
            uiresume;
            return
        end
    end
end